school_classes = ["FORM 1","FORM 2","FORM 3","FORM 4"]
library_classes = ["GENERAL","PRIMARY SCHOOL","JUNIOR SCHOOL","FORM 1","FORM 2","FORM 3","FORM 4","SENIOR SCHOOL","COLLEGE"]
staff_classes = ["ADMINS","SNR SCHOOL TEACHERS","JNR SCHOOL TEACHERS","RECEPTIONISTS","OTHERS"]
staff_roles = ["PRINCIPAL","DIRECTOR OF STUDIES","SENIOR TEACHER","HEAD OF DEPARTMENT","TEACHING PRACTICE","OTHERS"]
staff_loes = ["PHD","MASTERS","PGDE","DEGREE","DIPLOMA","CERTIFICATE","ARTISAN","FORM FOUR","CLASS 8","OTHER"]
student_roles = ["STUDENT (NO ROLE)", "PREFECT (HEAD BOY)", "PREFECT (HEAD GIRL)", "PREFECT (FORM 1)", "PREFECT (FORM 2)", "PREFECT (FORM 3)", "PREFECT (FORM 4)", "PREFECT (ENTERTAINMENT)", "PREFECT (DH)", "PREFECT (GAMES)", "PREFECT (ENVIRONMENT)", "PREFECT (DORM)", "PREFECT (TIME KEEPER)", "PREFECT (CU)", "PREFECT (OTHER)"]
                               